### ISSUE TITLE
能不能适配一下QQ音乐的歌词API呢？

### ISSUE THREAD

**Issue by rapon233** [LudySu/Synology-LrcPlugin#3]
网易有很多灰色歌曲就搜不到歌词了，比如说JAY CHOU

**Comment by LudySu** [comment]
当时想做的，没找到合适的API，QQ的和服务器通信都是加密的，还没人解密。其实QQ是最好的，支持翻译，卡拉OK。网易的是难得比较齐全又没加密的

**Comment by nolongerhesitate** [comment]
请问可以支持一下对繁体歌名的歌词的检索嘛？ 下载的整轨专辑，歌名是繁体的 就无法搜索歌词
