### ISSUE TITLE
请问下载的歌词保存到哪里去了呢？

### ISSUE THREAD

**Issue by eklim530** [LudySu/Synology-LrcPlugin#4]
您好，感谢您的辛勤付出。我想请问下下载的歌词保存到哪里去了呢？在ds audio上倒是能看到，但在歌曲文件夹下看不到。
另一个QQ的插件也是如此
谢谢您

**Comment by LudySu** [comment]
你好。在audiostation网页版本的播放器是即时下载的，没有保存；但是你点击歌曲信息进去，手动搜索歌词，点击“保存”后会保存到你NAS上歌曲所在目录。

DS audio手机版的不清楚，可以到app所在数据目录找找
