### ISSUE TITLE
好像不能用了？

### ISSUE THREAD

**Issue by anytalks** [LudySu/Synology-LrcPlugin#7]
好像不能用了？

**Comment by ariakeumi** [comment]
是的

**Comment by LudySu** [comment]
Yes. Tested, sad that Netease API now requires authentication.
Will need to provide a way/instructions for the user to get the auth token.

**Comment by fanzai0403** [comment]
change: http://music.163.com/api/search/pc
to: http://music.163.com/api/search/get/web
#8

**Comment by johnchlorophyll** [comment]
Thanks! It's working.
Bad news is now Netease will detect and block IP abroad.

Update: 
add the header to unblock the ip overseas
`CURLOPT_HTTPHEADER => array(
        "X-Real-IP: <any ip in China>"
 ),`

**Comment by anytalks** [comment]
> Thanks! It's working.
> Bad news is now Netease will detect and block IP abroad.
> 
> Update: 
> add the header to unblock the ip overseas
> `CURLOPT_HTTPHEADER => array(
>         "X-Real-IP: <any ip in China>"
>  ),`

Thx
