### ISSUE TITLE
适配 DSM 7.0 版本

### ISSUE THREAD

**Issue by misaka00251** [LudySu/Synology-LrcPlugin#9]

**Comment by crystalcamel** [comment]
给大佬端茶倒水~~感谢

**Comment by jiemi6** [comment]
已升级dsm7，端茶等大佬更新

**Comment by LudySu** [comment]
Now Netease is bocking oversea IPs, better to use another lyrics provider
Use this plugin instead: https://github.com/LightAPIs/qq_music_aum
